# Generated by Django 6.0.2 on 2026-02-17 10:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_key', models.TextField()),
                ('wa_id', models.TextField(blank=True, null=True)),
                ('phone_e164', models.TextField(blank=True, null=True)),
                ('profile_name', models.TextField(blank=True, null=True)),
                ('crm_contact_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'active'), ('closed', 'closed')], default='active', max_length=10)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp_inbound.contact')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp_inbound.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp_inbound.tenant'),
        ),
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_wamid', models.TextField(blank=True, null=True)),
                ('source_type', models.TextField(default='unknown')),
                ('ctwa_clid', models.TextField(blank=True, null=True)),
                ('source_id', models.TextField(blank=True, null=True)),
                ('headline', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('raw_json', models.JSONField(default=dict)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp_inbound.contact')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp_inbound.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('category', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('components_json', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp_inbound.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_template_name_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('in', 'in'), ('out', 'out')], max_length=3)),
                ('channel', models.CharField(default='whatsapp', max_length=32)),
                ('wamid', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('type', models.TextField()),
                ('text_body', models.TextField(blank=True, null=True)),
                ('payload_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp_inbound.contact')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp_inbound.conversation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp_inbound.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'contact', '-timestamp'], name='messages_contact_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'wamid'), name='uniq_wamid_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='MemoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(default='')),
                ('facts_json', models.JSONField(default=list)),
                ('active_primary_event', models.TextField(blank=True, null=True)),
                ('active_secondary_events', models.JSONField(default=list)),
                ('recent_events', models.JSONField(default=list)),
                ('scores_json', models.JSONField(default=dict)),
                ('last_user_message_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp_inbound.contact')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp_inbound.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'contact'), name='uniq_memory_per_contact')],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['tenant', 'contact', 'status'], name='conv_active_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['tenant', 'phone_e164'], name='contacts_phone_idx'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('tenant', 'contact_key'), name='uniq_contact_key_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='attribution',
            index=models.Index(fields=['tenant', 'contact', '-captured_at'], name='attrib_contact_idx'),
        ),
    ]
