# Generated by Django 5.2.11 on 2026-02-20 08:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_inbound', '0003_fill_tenant_key_and_business_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('max_points', models.PositiveSmallIntegerField(default=10)),
                ('triggers', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('freeform_reply', models.TextField(blank=True, default='')),
                ('template_key', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='whatsapp_inbound.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='whatsapp_in_tenant__abc0bf_idx'), models.Index(fields=['tenant', 'name'], name='whatsapp_in_tenant__866f68_idx')],
                'unique_together': {('tenant', 'name')},
            },
        ),
    ]
