# Generated by Django on 2026-02-21
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_inbound', '0004_tenantevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='language',
            field=models.TextField(blank=True, default='es_AR', null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='components_json',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='template',
            name='meta_status',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]

