# Generated by Django 5.2.11 on 2026-02-22 06:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_inbound', '0005_template_meta_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('INBOUND_SAVED', 'INBOUND_SAVED')], max_length=64)),
                ('tenant_id', models.CharField(db_index=True, max_length=128)),
                ('contact_key', models.CharField(db_index=True, max_length=128)),
                ('turn_wamid', models.CharField(db_index=True, max_length=256)),
                ('dedupe_key', models.CharField(max_length=512, unique=True)),
                ('payload_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('sent', 'sent'), ('failed', 'failed'), ('dead', 'dead')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tenantevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tenantevent',
            name='max_points',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='tenantevent',
            name='triggers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='tenantevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
