# Generated by Django 5.2.11 on 2026-03-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_inbound', '0006_outboxevent_alter_tenantevent_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryrecord',
            name='sales_state_json',
            field=models.JSONField(default=dict),
        ),
    ]
